Integrated spherex's proxy in InitializableUpgradeabilityProxy.
starlay-finance/starlay-protocol pull request #239
Opened 2024-03-07 14:15 UTC by idoh-spherex

2024-03-08 01:29 UTC, wolfwarrior14 approved these changes

2024-03-08 01:32 UTC, wolfwarrior14 requested changes

2024-03-08 01:32 UTC, ghost commented on contracts/dependencies/spherex/ISphereXEngine.sol
> +// (c) SphereX 2023 Terms&Conditions
Could you specify the solidity version?

2024-03-10 12:48 UTC, ArielTM commented on contracts/dependencies/spherex/ISphereXEngine.sol
> +// (c) SphereX 2023 Terms&Conditions
Done

2024-03-11 00:53 UTC, wolfwarrior14 approved these changes

2024-03-11 00:54 UTC, merged